// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// computeR0bar
double computeR0bar(NumericVector vec, int numPerm);
RcppExport SEXP _sharpeRratio_computeR0bar(SEXP vecSEXP, SEXP numPermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type numPerm(numPermSEXP);
    rcpp_result_gen = Rcpp::wrap(computeR0bar(vec, numPerm));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sharpeRratio_computeR0bar", (DL_FUNC) &_sharpeRratio_computeR0bar, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_sharpeRratio(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
